### ISSUE TITLE
Persistent storage of access token via SecretManagement

### ISSUE THREAD

**Issue by krokofant** [AZDOPS/AZDOPS#100]
**Is your feature request related to a problem? Please describe.**
Right now it seems you need to reconnect to ADO for each new PowerShell session you start.

**Describe the solution you'd like**
The [SecretManagement module](https://github.com/PowerShell/SecretManagement) could be used to store the access token locally. It can be secured with a passphrase.

**Additional context**
N/A

**Comment by PalmEmanuel** [comment]
That's a good suggestion, although it would mean another dependency for the module.

We've been planning to leverage the cache functionality of other services using the Azure.Identity library so that the user can connect with the same token as they already use in shared Microsoft services, Azure PowerShell, Az CLI, Visual Studio etc, or even an interactive browser login. This will likely be done using [AzAuth](https://github.com/PalmEmanuel/AzAuth) which I wrote for that purpose.

I wonder if there's a use case for the SecretManagement module functionality as well, do you see a situation where you would still want to save a token specifically for usage within this module that wouldn't be covered by that implementation?

**Comment by bjompen** [comment]
I think that's a great idea, but like @PalmEmanuel said, it adds a dependency.
I don't think we should add too much complexity as it would beat one of the key principles ("simplicity") of the project,

Maybe an option would be to have `Connect-ADOPS` and the internal functions have parameters for "StoreInSecretManagement" and "StoreInAzAuth", and if given one of this it will check if the module is installed and if not throw an error or smth? I don't know how this would look, but a test implementation could absolutely be worth discussing.

**Comment by bjompen** [comment]
This will be done, but in a different way and released as breaking version 2.0 instead.
