### ISSUE TITLE
Connect-ADOPS -OauthToken from Pipeline

### ISSUE THREAD

**Issue by coolhome** [AZDOPS/AZDOPS#202]
**Describe the bug**
The `System.AccessToken` in an Azure Pipeline is valid for some of these API calls but is not possible because of these two endpoints:

* https://app.vssps.visualstudio.com/_apis/accounts
* https://app.vssps.visualstudio.com/_apis/profile/me

https://github.com/AZDOPS/AZDOPS/blob/e1d7bcadd24ea125405100ba3979370e18f8e95e/Source/Public/Connect-ADOPS.ps1#L63-L66

**To Reproduce**
Run Azure Pipeline likes the following:
```yaml
steps:
 - pwsh: |
    Install-Module ADOPS -Scope CurrentUser -Force
    Import-Module ADOPS
    Connect-ADOPS -Organization "$(System.CollectionUri)" -OAuthToken "$(System.AccessToken)"
```

**Expected behavior**
There should be no issue to pass the Pipeline App Token to pull some of these resources.

**Comment by bjompen** [comment]
Interesting, and a scenario I haven't tested. Most likely I would guess the scope of the token from the pipeline isn't set correct.
I'll dig in to it to see if and how to fix. Pinging in @PalmEmanuel as well as he may know something from the AzAuth module.

**Comment by coolhome** [comment]
A pipeline token is not that user of ADO so I imagine these routes will also find nothing. The scope require is `vso.profile` for both.

**Comment by bjompen** [comment]
The main issue isn't finding nothing, the call returns an "log in" page, which we manually throw as a filed login.
This is what happens if we remove ADOPS and run the same manually:
![image](https://github.com/AZDOPS/AZDOPS/assets/17783007/78831553-3f7e-4f87-8de5-9a03980073aa)

Since the accesstoken is scoped either as proj or org I would say it may be hard, not to mention pretty useless, to even grant it access to external endpoints. How about adding a "SkipVerification" switch that simply bypasses this check and creates the token anyway?
We ( c | sh )ould also include a verbose message to it saying something like "since we wont verify this connection it is up to you to make sure it works."

Would that be a good solution?

**Comment by bjompen** [comment]
I've added a PR to implement this, but would be happy to get some feedback.
Since I haven't implemented pre-releases yet you can test it by cloning the code from the linked PR, #203 , and importing it manually to your repo.

I tested it using the following yaml and it seems to work as expected.

```yaml
- pwsh: |
    Install-Module AzAuth -Force -Verbose
    Import-Module AzAuth
    Import-Module $(Pipeline.Workspace)/s/adops/Source/ADOPS
    Connect-ADOPS -Organization "$(System.CollectionUri)" -OAuthToken "$(System.AccessToken)" -Verbose -SkipVerification
    Get-ADOPSProject
```

If you this this is a viable solution I can merge and create a minor release right away.

**Comment by coolhome** [comment]
@bjompen I think this is sufficient! 

I had an alternative idea where I would introduce something like `Set-ADOPSOauthToken` since majority of the cmdlets support passing the organization in.

**Comment by bjompen** [comment]
We had discussions earlier on setting default org, as this was supported in v.1 of the module (with PAT tokens). I don't really remember now why, but there were issues with it and adding it may require a bit more restructure of login behaviour. I am absolutely open to a discussion about it, but lets see what is needed first.
